fieldLayouts:
  f7429967-b88d-4b4f-a50f-2baa1ed3b3f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b50956ff-ff05-4343-81f4-64811f06aaf0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65528c1b-d8f2-489a-a900-cbe119758582
        userCondition: null
handle: frontpage
hasTitleField: false
name: Frontpage
section: c949657b-0502-4133-8267-addc74137f57 # Frontpage
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
