defaultPlacement: end
fieldLayouts:
  52e6a072-98e4-4490-8ecb-4eb83fdbdb9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 79696161-f7f0-467e-94fa-03692c319c13
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21294ef0-591f-401a-806e-4e715ed24146
        userCondition: null
handle: categories
name: Categories
siteSettings:
  ab9559a5-3d52-468a-8d8d-1b8fc47d67ec: # Wago
    hasUrls: true
    template: _categories/index.html
    uriFormat: 'weakauras/categories/{slug}'
structure:
  maxLevels: null
  uid: bce9ca91-ab36-4034-8427-33d153584014
