defaultPlacement: end
enableVersioning: true
handle: frontpage
name: Frontpage
propagationMethod: all
siteSettings:
  ab9559a5-3d52-468a-8d8d-1b8fc47d67ec: # Wago
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
